#!/bin/bash
cd $HOME/cs350-os161/os161-1.99
./configure --ostree=$HOME/cs350-os161/root --toolprefix=cs350-
cd kern/conf
./config $1
cd ../compile/$1
bmake depend
bmake
bmake install

#building the OS/161
#d $HOME/cs350-os161/os161-1.99
#bmake
#bmake install
